### ISSUE TITLE
No option to set timeout

### ISSUE THREAD

**Issue by cfloisand** [krismuniz/botkit-sms#12]
According to the Botkit docs, there should be a function you can call on a conversation to set the timeout interval in milliseconds `convo.setTimeout(...)` as well as a way to set a timeout handler `convo.onTimeout(...)`. Trying to set both of these using botkit-sms results in a failure, saying that `setTimeout` and `onTimeout` are not functions. Looking at the Botkit library included by botkit-sms, it looks like these functions are nowhere to be found. So is botkit-sms using an outdated version of Botkit, or is there another issue causing this? 

Is there a way to set the timeout of a conversation, because with testing, no timeout occurs as far as I can tell, which is problematic.

**Comment by krismuniz** [comment]
Yes. Botkit has changed. I will include the new Botkit as a dependency and publish a new version.

Thank you very much for finding this!

(By the way, I made a PR on Botkit to include SMS as a platform, let's hope it gets merged soon!)

**Comment by krismuniz** [comment]
Done! I just published `botkit-sms@1.2.1`!

### Changes:

- [x] Updated `botkit` dependency to latest version.

Update your `botkit-sms` dependency to see the new changes :)

Have a nice day!

**Comment by cfloisand** [comment]
Awesome, thanks!
