### ISSUE TITLE
Send image?

### ISSUE THREAD

**Issue by prichey** [krismuniz/botkit-sms#14]
I'm wondering if it's possible to send an image. I see Botkit generally supports image attachments via `bot.reply(message, {attachments: [...]})` but I can't get it to send via Twilio. It's definitely possible to send MMS via Twilio (https://www.twilio.com/docs/api/rest/sending-messages), I'm just trying to figure out how to do it via botkit. Thanks!

**Comment by krismuniz** [comment]
Greetings @prichey!

I just published `botkit-sms@1.3.0` to npm with media attachment support. Update your `botkit-sms` package and you will be able to send media (including images).

### Usage

To send image attachments as well as other kinds of media just set `mediaUrl` property of your outgoing message object to the url of your choice (See [Twilio's Documentation] (https://www.twilio.com/docs/api/rest/accepted-mime-types) for a list of allowed MIME Types).

You may also include an optional `body` to go along with your attachment.

```js
bot.reply(message, {
  body: 'Optional body to go with text',
  mediaUrl: 'https://i.imgur.com/9n3qoKx.png'
})
```

Thank you for your contribution!

**Comment by prichey** [comment]
Wow! Thanks so much for taking care of that. 👏 Cheers!

**Comment by prichey** [comment]
It looks like the fix introduced some breaking changes. Running your example program, I get the following output:

```
Initializing Botkit v0.5.4
info: ** No persistent storage method specified! Data may be lost when process shuts down.
info: *> Listening on port 3000
info: *> Serving webhook endpoint BE7700:3000/sms/receive
TwilioSMSBot is online!
info: => Got a message hook
info: [Start]  0  Task for  +13169905723 in +13169905723
info: >   [Start]  0  Conversation with  +13169905723 in +13169905723
null
info: An error occurred while sending a message:  { status: 400,
  message: 'Media urls:  are invalid. Please use only valid http and https urls',
  code: 21620,
  moreInfo: 'https://www.twilio.com/docs/errors/21620' }
info: An error occurred while sending a message:  { status: 400,
  message: 'Media urls:  are invalid. Please use only valid http and https urls',
  code: 21620,
  moreInfo: 'https://www.twilio.com/docs/errors/21620' }
```

I fixed the errors by changing 
```
let sms = {
  body: message.text,
  from: configuration.twilio_number,
  to: message.channel,
  mediaUrl: message.mediaUrl || undefined
}
```

to

```
let sms = {
  body: message.text,
  from: configuration.twilio_number,
  to: message.channel
};

if ('mediaUrl' in message) sms.mediaUrl = message.mediaUrl;
```

I'll submit a PR with the above fix. Thanks!
