### ISSUE TITLE
Push 1.3.1 to npm

### ISSUE THREAD

**Issue by pjvdl** [krismuniz/botkit-sms#16]
Hi Kristian,

Great work on this. I have been using botkit-sms 1.3.0 from npm over the last couple of days and hit your issue with mediaUrl. I note that you have fixed this in github and released 1.3.1, but it has not been pushed to npm.

Can you please push 1.3.1 to npm?

Thanks.

**Comment by krismuniz** [comment]
Oops, sorry for that! 

I just published `botkit-sms@v1.3.1`

Thank you for your contribution!

**Comment by pjvdl** [comment]
Thanks!
