### ISSUE TITLE
Cannot set property 'channel' of undefined

### ISSUE THREAD

**Issue by thierryskoda** [krismuniz/botkit-sms#8]
Can anyone help me with this ? :( 

![screen shot 2016-08-25 at 12 50 24 pm](https://cloud.githubusercontent.com/assets/6875849/17978107/864e9ed6-6ac2-11e6-9b50-56ef5728b87b.png)

Thank you in advance!

**Comment by krismuniz** [comment]
Sure! My prediction is that you tried to reply to the message like this:
```js
bot.reply('My reply')
```
However you need to pass the user's message first and *then* your reply message. Like this:
```js
bot.reply(message, 'My reply')
```
If this didn't solve your problem, can you share the piece of code that isn't working?

**Comment by thierryskoda** [comment]
Yes it solved my problem! :) I did another issue request about the doc because in your example, you wrote ```bot.reply('my reply')```
